spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: mbacke
    password: mbacke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: bmbacke
    password: bmbacke
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/book-social-network"
application:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  file:
    uploads:
      photos-output-path: ./uploads

  security:
    jwt:
      secret-key: EzlKRzeO3KNOmxBKbrpUdaPrqtl0JAZbEUfQX798k0A=
      expiration: 86400000

server:
  port: 8088



